image: ubuntu:18.04

before_script:
  - apt-get --quiet -qq update
  - apt-get --quiet -qq install perl-modules git cmake g++ libio-socket-ssl-perl libyaml-perl

test:
  stage: build
  script:
    - prove -I modules
